### ISSUE TITLE
animalia cows are tending to die off and dont seem to give milk as expected 

### ISSUE THREAD

**Issue by yampertx** [Freebi85/Dungeons-Dragons-Space-Shuttles#130]
The cows I am breeding are unresponsive to feeding and watering the water bucket floats above the head I am clicking with a bucket to water them but they don't accept water also I have bred them they drop calves they are saying ready to milk but not giving milk 
Then at times when I leave them at full health I come back to find they have died without warning.

Is there any chance we could add normal MC cows just to do the quest line for cheese  etc 
sorry if this is the wrong place to ask

**Comment by Freebi85** [comment]
Basically the animals cannot just die when they are thirsty or hungry because this is turned off by default. There is something wrong with the configs or they have been changed. The animania animals are sometimes a bit tedious, but that's basically true if they have enough space and water surfaces/through it works pretty well. I use a ranger to milk the cows.

From the description you can see:
Milk is made by milking Cows, Goats or Sheeps with an empty bucket. In order to be able to milk animals they have to be happy (fed and watered), mated with a partner and have given birth to an offspring. Later you can use the rancher from industrial foregoing to automate the milking process. Note: Animania creatures need a lot more space than the regular minecraft animals.

Here still the Wiki link perhaps you find here information I forgot =)
http://www.animaniamod.net/index.php/Animals

You can't turn off the mod Animania or all recipes will be broken. At the most you can add to the animania configs vanilla cows. (enabled = true)
