### ISSUE TITLE
Cant Install on twitch Lanucher

### ISSUE THREAD

**Issue by linkboyrocks** [Freebi85/Dungeons-Dragons-Space-Shuttles#178]
It gives me the error "The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters , and the directory name must be less than 248 characters."    If there is something im missing help would be appreciated.

**Comment by Freebi85** [comment]
Hello =)
I'm afraid I can't help you with that. Twitch often has some pointless problems. All I can recommend is to use MultiMC instead of twitch. If you need more informations about this you can always join our Discord Server.

**Comment by Nbenito** [comment]
I have possibly figured out this problem for future reference.
TL, RD: Change the location of your instances to a folder that is closer to the main drive location.
Instead of: E:\user\Minecraft\Personal\Minecraft Files\TwitchCurse Minecraft\Instances
Do instead: E:\Minecraft\Minecraft Files\Instances

I got this same issue recently and when I read the error again, I thought it might be the location of the file where all the instances are at. 
So I experimented and when I changed my folder from a file path of "E:\user\Minecraft\Personal\Minecraft Files\TwitchCurse Minecraft\Instances" to a file path of "E:\Minecraft\Minecraft Files\Instances," The mod pack downloaded like normal.

I believe the twitch launcher got a hiccup when it was trying to download and notice there were too many paths it had to navigate to find the instances folder. So it decided to quit running. So for anyone with this problem, try to shorten the path to your instances and it might work and download for you.
