### ISSUE TITLE
Make a Discord channel for pack?

### ISSUE THREAD

**Issue by billyty08** [Freebi85/Dungeons-Dragons-Space-Shuttles#19]
I was thinking it would be great if there was a public Discord channel just for your packs linked from the modpacks page on Curse for people to go and chat about things in the pack. Bounce ideas off each other and ask questions about things unfamiliar to them. I enjoy having a place to go and share what little knowledge I have and get some from others and I am sure others do as well. Again loving the pack and hope it get really popular.

**Comment by billyty08** [comment]
I have another small suggestion. Maybe add a checkbox quest that will run the /bq_admin default load command for when people update pack. I am not sure if it is a must but might be helpful for those not familiar with having to do it. I've seen it in other packs and thought it a good idea

**Comment by Freebi85** [comment]
Hello my friend ^^
Since this morning we have a official Discord Server. (
currently a bit empty^^) 
Here  ist the Link.
Discord Link: https://discord.gg/eUajYmK

I will consider your suggestion with a Checkbox Quest.

Sadly Mr. Crayfish has no config Files to turn off this annoying update checker^^ He does not want to fix that at the moment :(
