### ISSUE TITLE
creepers blowing everything up

### ISSUE THREAD

**Issue by uhDreamer** [Freebi85/Dungeons-Dragons-Space-Shuttles#222]
There's a giant ring of craters around my base from random creeper explosions (I'm guessing from mobs fighting each other) and it's really gross to look at and at points hard to even cross. is there a way to fix this that anyone could recommend? I've no idea what mod from the pack would affect this, nor to to turn that specific feature off

**Comment by Freebi85** [comment]
Hello =)
1. Possibility: You can claim the chunks around your base with ftbutils so creepers cannot do any damage to the terrain.
2. Possibility: Illuminate a large area around your base so that no creepers spawn at all.
3. Possibility: Craft a Mega Torch. It prevent mob spawn around 64x64 blocks radius
4. Possibility: Turrets!! xD
5. Turn off some specific configs.... if you really want to remove this I will gladly give you instructions in Discord (DM me)
Discord Server Link: https://discord.gg/eUajYmK

Freebi
