### ISSUE TITLE
RFTools Mob spawners

### ISSUE THREAD

**Issue by Cormenthor** [Freebi85/Dungeons-Dragons-Space-Shuttles#249]
Once a syringe has been placed into the spawner if you take it out and replace it with a different one it crashes the game and corrupts your world. Since I've never used these spawners before I'm not sure if this is normal or not. But I'm thinking it not so posting here so maybe others can be warned about it/

**Comment by Freebi85** [comment]
Hello =) Thx for reporting but this mod specific issue is already reported to RFTools.
https://github.com/McJtyMods/RFTools/issues/1967
There are different crash situations with sysinges. You can Share your crash report there to helping the devs fix the issue.

I will close this one because I can't fix this myself and the Devs are already informed.
