### ISSUE TITLE
Astral sorcery collector crystal problem

### ISSUE THREAD

**Issue by RusMephist** [Freebi85/Dungeons-Dragons-Space-Shuttles#250]
Pumpkins don't turn into cakes by Collector Crystals.

![2019-08-07_23 08 34](https://user-images.githubusercontent.com/52924343/62654485-9475db80-b968-11e9-9978-0a824998eb23.png)

**Comment by weightmaker** [comment]
i still have the same problem. i assume it was mistakenly removed along with the removal of  iron ore -> starmetal ore recipe

**Comment by weightmaker** [comment]
nvm, i see you manually removed it and added it to the infuser. you might want to change the quest "Transmutations" to say that you removed the cake and starmetal ore transmutation ++. i assumed this was a bug due to the questbook info atleast. 

source: Line 87 in /scripts/Recipes/Astral Sorcery.zs

**Comment by Freebi85** [comment]
Thank you for the hint.
