### ISSUE TITLE
Very high TPS

### ISSUE THREAD

**Issue by Tntdruid** [Freebi85/Dungeons-Dragons-Space-Shuttles#255]
Made a new world wait for like 5 min did a /forge tps

This is in Peaceful 

![2019-08-09_10 31 34](https://user-images.githubusercontent.com/72948/62765764-1c570500-ba91-11e9-9ee9-47e59d7b96fe.png)

This is in Normal

![2019-08-09_10 33 56](https://user-images.githubusercontent.com/72948/62765873-5e804680-ba91-11e9-82dc-66b089038876.png)

No idea whats is going on.

**Comment by Freebi85** [comment]
Hi =)
To be honest with this informations, it's not really possible to help. I suggest to join our Discord Server in the support dchannel and then we will look together what the problem is and analyze your pc specs and settings to optimize the experience of this pack :D

Discord Server Link: https://discord.gg/eUajYmK
