### ISSUE TITLE
Nether Portals

### ISSUE THREAD

**Issue by BoricEloopy** [Freebi85/Dungeons-Dragons-Space-Shuttles#297]
When creating nether portal the return never takes you back to original launch just keeps recreating others Destroy them Build over. it just recreates a few blocks away

**Comment by cyber01** [comment]
It looks like your portal system is corrupted. This is an old problem in minecraft itself. It happens when one of the portals (most often in the nether) is destroyed.
It can be fixed using the mod https://www.curseforge.com/minecraft/mc-mods/netherportalfix only with you or if @Freebi85  adds it to the modpack

**Comment by Freebi85** [comment]
Cyber01 is right. There is no much i can do for you at this point. i will consider to add the mod in a further update so that this problem can be ruled out.
