### ISSUE TITLE
enhancement: More creative item recipes. + buff up creative power source recipe

### ISSUE THREAD

**Issue by DragonmasterDJ** [Freebi85/Dungeons-Dragons-Space-Shuttles#3]
I wanted to know, looking over the creative power source recipe It seems kind of bland. Once you can get up to the stage of getting the ultimate crafting table it seems pretty straight forward. Maybe some items in the recipe could be replaced with more high tier items. Like ludicrite, which might get its own recipe etc. 

Also another thing in is that maybe there could be end- end game creative item recipes such as infinite items upgrade for a drawer, or maybe a creative tank, gas tank, mana pool, mill, etc?

These are just suggestions, thank you for reading! ^^

**Comment by Freebi85** [comment]
Hello Dragonmaster =)

That's completely understandable. It's also in my interest to expand the Elite & Ultimate Crafting Table with many more recipes. I'll do my best. It takes time for me to fully concentrate on the ultra endgame because I still have a long way to go. I would like to thank them for the proposals they are making. 
I will certainly implement some of it.

**Comment by Freebi85** [comment]
I will certainly add more of your suggestions over time. The Energy Cell has also been reworked. But for the moment I'm closing here.
