### ISSUE TITLE
part of zombie hordes spawning half inside blocks not able to move

### ISSUE THREAD

**Issue by arturgaweski** [Freebi85/Dungeons-Dragons-Space-Shuttles#30]
As in title & screenshot, except little AI problems it look like sometimes zombies keep spawning inside dirt or other nearby blocks near my base (but not inside atleast).

This isn't lag issue, CPU at max. 60%, GPU at max. 15%, RAM 8 GB (3,8 GB used), SSD drive for minecraft.

![2018-12-08_13 52 32](https://user-images.githubusercontent.com/45362992/49686160-c93b4580-faf0-11e8-93c4-e21b9ffec330.png)

**Comment by Freebi85** [comment]
This is probably coding problem of zombie awarness. Everything about coding must be reported to the mod author. The mod itself has not been updated for a long time. If the errors increase, I'm gonna have to remove this.

As a modpack manufacturer I can only change the spawnrate or adjust recipes. Such bugs cannot be fixed by me. Maybe the new forge version fixes some bugs.
