### ISSUE TITLE
"Minecraft failed to start"

### ISSUE THREAD

**Issue by GamerMilo** [Freebi85/Dungeons-Dragons-Space-Shuttles#324]
Heya,
When I try to launch the pack my Minecraft experiences an error during startup, and failes to start. It says: "The following mods have been identified as potential causes:
Quark, CraftTweaker2, CT-GUI, CraftTweaker, JEI Support, Just Enough Items"
Of course, I don't know how you could be able to help me with this, but this pack seems really cool and I don't know what to do to fix this.
The error file:
https://paste.dimdev.org/akazuwagup.mccrash

**Comment by cyber01** [comment]
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded

You need allocate more RAM for minecraft (minimum 6gb, recommended 8+)

Don`t use issues for crashes

Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK
