### ISSUE TITLE
Quests? 

### ISSUE THREAD

**Issue by uncureablebos56** [Freebi85/Dungeons-Dragons-Space-Shuttles#348]
When i try to view the quests i just get a blank page.

https://gyazo.com/e62b18a4fe606b3ad089baa79780bb25

From what ive seen the game runs perfectly fine though

**Comment by Danekjovax** [comment]
Try this command:

/bq_admin default load

And then see if you can see your quests.

**Comment by Freebi85** [comment]
Danek is right. Maybe your questfiles are corrupted if everything else works fine.
If you have to recover your quest progression try following steps:

Aroma makes regular backups so that nothing is lost. Go to your backup folder and open "saves-->your world". Look for the "betterquesting" folder in the save, and copy "quest database" and "quest progress" files and paste them in the same folder of your primary world.

If you started questing for the first time /bq_admin default load should fix it,

If not reainstall the pack, I guess something probably went wrong in twitch. Once again^^

**Comment by DloobyOwl** [comment]
> Danek is right. Maybe your questfiles are corrupted if everything else works fine. If you have to recover your quest progression try following steps:
> 
> Aroma makes regular backups so that nothing is lost. Go to your backup folder and open "saves-->your world". Look for the "betterquesting" folder in the save, and copy "quest database" and "quest progress" files and paste them in the same folder of your primary world.
> 
> If you started questing for the first time /bq_admin default load should fix it,
> 
> If not reainstall the pack, I guess something probably went wrong in twitch. Once again^^

Hi, I'm also having this problem of the empty quest book
I tried the command / bq_admin default load but it comes out in chat: _"quest database not found"_
I tried to reinstall the pack 3 times and in all three it doesn't load the quests
what should I do?
Result in chat [https://imgur.com/a/fm9GdSs](url)

As is the quest book, both from outside the "quest" section and inside
[https://imgur.com/a/XnNgwPW](url)
[https://imgur.com/a/szoEmJJ](url)
