### ISSUE TITLE
Tungsten unable to be processed in Industrial Blast Furnace

### ISSUE THREAD

**Issue by Synestheoretical** [Freebi85/Dungeons-Dragons-Space-Shuttles#370]
A max-heat Industrial Blast Furnace from Tech Reborn (Multiblock formed from Advanced Machine Casings with 2 lava blocks in center) is only reaching 2880 heat, Tungsten and several other processes require 3230
![report1](https://user-images.githubusercontent.com/26726769/66024972-5659eb80-e4c3-11e9-89cc-a7dfa22a3aad.png)
![report2](https://user-images.githubusercontent.com/26726769/66024988-5fe35380-e4c3-11e9-805b-deaf39c34eb7.png)
![report3](https://user-images.githubusercontent.com/26726769/66024994-6671cb00-e4c3-11e9-9be4-091940f13e02.png)
![report4](https://user-images.githubusercontent.com/26726769/66025008-6b367f00-e4c3-11e9-8a81-0ee7c5ce64f0.png)

version 5.7b
Multiplayer, server, unaltered server files downloaded from Twitch Launcher

**Comment by Freebi85** [comment]
Hello =)
I't dosent work this way anymore. You need to put 4 Kanthal heating coild and 4 nichrome heatoing coil to the core block (right click on it) it's a new TechReborn mechanic since latest update. The advanced machines casings are still required.

Additional Quests are in version 6.x for this. of yourse you need to update version and questbook as well^^
