### ISSUE TITLE
Cannot complete quest smeltery #2.

### ISSUE THREAD

**Issue by jstepp3** [Freebi85/Dungeons-Dragons-Space-Shuttles#371]
When you have the quest book open it doesn't show a picture of Grout, it is a blank frame and it says "AIR" over the frame and I cannot complete the quest even though I have more then enough grout to do so.  If you could advise I would be eternally grateful, Im loving the pack so far.  I did add the mod "ore Excavation.  I tried disabling it but it does nothing.

**Comment by JurasTW** [comment]
Confirming that issue still present in 6.1
![2019-10-02_21 46 43](https://user-images.githubusercontent.com/38030680/66072677-2875b500-e55e-11e9-8710-275daa5b0b81.png)
refreshing the questbook mod didn't help.

P.S. the modpack does seem tedious without any sort of vein miner, i know it supposed to be a reward with thinker stuff to chop trees and stuff, but digging sand and gravel is horrible, especially since gravel does not recognize a mattock as a shovel so no bonus speed is applied. so yeah, not required but is not adding any fun at all since tinkers is locked away for a few hours

**Comment by jstepp3** [comment]
Ok I am a bit of a dumbass, after a bit of more looking I saw this was already a known issue and was fixed in the new pack.  I had to look up how to update the quest book.  (Im a noob) I got it fixed now, sorry if I wasted anyones time.

**Comment by JurasTW** [comment]
> Ok I am a bit of a dumbass, after a bit of more looking I saw this was already a known issue and was fixed in the new pack. I had to look up how to update the quest book. (Im a noob) I got it fixed now, sorry if I wasted anyones time.

huh? refreshing didn't help me. how did you update?

**Comment by jstepp3** [comment]
The way it fixed for me was to go to my saves and rename my "questdatabase.jason so that it had to redownload it.  I noticed all other fiels were up to date but that one was several days out.  this fixed the issue.

**Comment by jstepp3** [comment]
https://www.youtube.com/watch?v=Vt1pnmXKqwA

**Comment by jstepp3** [comment]
video I watched that gave the idea

**Comment by jstepp3** [comment]
I really hope it works for you as well.

**Comment by JurasTW** [comment]
yeah, renaming the old file and loading up the world again helped! Thank you, though this solution should be pinned for a while to help with the confusion on doing existing worlds in the new version.

**Comment by jstepp3** [comment]
Just glad I could help.

**Comment by Freebi85** [comment]
It’s fixed in 6.1 you can refresh the questbook with an ingame command /bq_admin default load or just hit the new update button inthe too right corner when opening the questbook after a new update. Not needed to rename entire files.
