### ISSUE TITLE
Orange Juice Bottle - OreDict overload?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#417]
I think the screenshot speaks for itself. ;2)
![2019-10-13_13 55 05](https://user-images.githubusercontent.com/10191173/67059426-fac86880-f126-11e9-9c10-b15d3d2c826f.png)

**Comment by Freebi85** [comment]
You are playing with advanced tooltips when pressing F3+h^^ That's more something for devs and pack makers^^ All Juice's from Binnis have multiple oredict entries instead of one. Of course this could have been solved more cleanly by the mod author.

But it is superfluous to adjust all oredict entries for 18 different juices. It doesn't harm or break the gameplay and is not visible to the "normal" player by default^^

**Comment by Danekjovax** [comment]
Yes, I am using the advanced tooltips, and OK, I'll stop worrying about the Oredict Overload. ;2)  Thanks.
