### ISSUE TITLE
Astral Sorcery crafting not working

### ISSUE THREAD

**Issue by HelpImDying** [Freebi85/Dungeons-Dragons-Space-Shuttles#422]
I have been trying to do any crafting in the Astral Sorcery, Luminous Crafting Table. I have taken the table and put it some where high up, around y = 132 and made sure there is nothing blocking the sky. When i up the items into craft at night the starlight bar fills but until full but i am never able to craft the items. Right clicking with the resonating wand doesn't have any effect.

**Comment by Freebi85** [comment]
Hi =)
Did you crafted the luminious crafting table yourself? Because astral sorcery is gated behind personal progression, so everyone have to craft their own tables and stuff. 
If yes then it's possible that the astraltome didn't detected your luminous craftingtable for some reason. Just try to craft it again or cheat one in.
Join our discord Server for more help :) (tech support channel)

**Comment by HelpImDying** [comment]
I have done everything you mentioned here i also tried using the astral sorcery commands to grant myself the knowledge and didn't receive it.
