### ISSUE TITLE
Hooked red hook has double jump to retract all hooks

### ISSUE THREAD

**Issue by Vendet29** [Freebi85/Dungeons-Dragons-Space-Shuttles#428]
Only red hook from hook mod has double jump to retract hooks. It's very inconvenient, clunky, unpractical, and it make you jump after retract, it's more like downgrade than upgrade.

Sugesstion: change red hook retract(keybind) to jump insed of double jump.

**Comment by Freebi85** [comment]
I can't change how the mechanic of a hook works. You need to suggest this directly to the mod author.
If this can simply be changed via Keybind you can change it for yourself. This would have no effect on further patches because your keybind will remain unaffected by updates. As long as you don't re-download the pack from scratch.
