### ISSUE TITLE
Loss of inventory without grave spawn or key on death with the "delay death" effect on. 

### ISSUE THREAD

**Issue by Xellyia** [Freebi85/Dungeons-Dragons-Space-Shuttles#462]
A repeating issue upon dying with the delay death effect, no key, no grave stone message and no glowing box where the grave would spawn.

**Comment by Danekjovax** [comment]
Could you please detail the steps you've done to repeat this issue?

**Comment by Xellyia** [comment]
1. Be affected by delayed death (once by a boss witch mob, other by a halloween candy I believe)
2. Die, both times had been from mobs, possibly zombies if that matters
3. Respawn and have no key or grave spawn message. Only "Death took its toll on (my character's name)."

I used the ob_inventory restore command to get my inventory back but could pose a bigger problem for other players.

**Comment by Freebi85** [comment]
I can't help you much there. You can use a backup to restore only your own invetory because I'm assuming you're playing on a server. The Halloween event from Corails was the problem with non appearing Gravestones. If the event is still going on you can disable it manually for everyone in the tombstone configs afaik.
