### ISSUE TITLE
Required progression skip in Tier 2 Main Quest with Vertical Digger & Dyonite

### ISSUE THREAD

**Issue by CloudyDash** [Freebi85/Dungeons-Dragons-Space-Shuttles#482]
In main quest tier 2, there is a quest requiring of you to make a Vertical Digger, which needs a Dyonite Pickaxe head to craft. The process to create Dyonite is taught in Tier 2 Ores, Alloys and Smeltery, but the quests to learn how to do so have prerequisites requiring a Rolling Machine, which is made in Tier 3 Main quest. Simply removing the requirement to complete the quest for Refined Obsidian ingots would fix the issue, allowing the player to proceed with the quests to make Dyonite without having to skip ahead and make Dyonite despite the quests being unavailable. 

While this is a minor issue, and anyone could simply make the Dyonite since the Refined Obsidian isn't used in it and ignore the quests until they can unlock them, it's out of place since you have been able to follow the questlines without breaking quest progression up to that point.

**Comment by Freebi85** [comment]
it's already been reported to me at the discord but thanks for your attention anyway! The vertical Digger has anyway only mining lvl cobalt so it will require a cobalt pick in next update.
In additions, Refined Glowstone and Obsidian becomes a optional quest because isn't required anyway for the TAIGA path progression in AOS Tier 2 at all.
Cheers
