### ISSUE TITLE
Won't open after I updated

### ISSUE THREAD

**Issue by tonicxp** [Freebi85/Dungeons-Dragons-Space-Shuttles#499]
After I updated the modpack, it wouldn't open no more. The minecarft launcher would open up, but after I clicked play it would't load the game. I've tried restarting, repairing , allowed more memory.

**Comment by Freebi85** [comment]
That's a common Twitch Issue after updating packs. You can try restart your pc or reinstall the pack to a new profile. Or most players move to MultiMC because of all the issues with the twitch launcher. For more help user our tech support in our discord Server. This is not a Pack-related Issue.
Thanks.
