### ISSUE TITLE
(suggestion) Replace questbook reward shop with omnifactory-style coin recipes.

### ISSUE THREAD

**Issue by TDSSS** [Freebi85/Dungeons-Dragons-Space-Shuttles#529]
Using the quest book rewards shop is generally pretty clunky in my experience, and it is pretty damn hard even knowing what's all available. I know this is a long shot but any chance you could replace it with the system omnifactory uses (which also replaced its quest book shop). 

In omnifactory certain patterns of coins simply craft into the reward items, so for example in this pack a certain configuration  of bronze coins would give you this sapling, a combo of gold coins would give you a spawn egg, etc.

**Comment by dierke9** [comment]
I see the reason for you asking this yet im uncertain if it would be a smart idea to do this. There are ceveral "problems" with this approach.
First of all there are shoprewards that give your multiple items (like the sappling bundles) second of all you loose the cooldown timers which are there for a reason.

**Comment by Freebi85** [comment]
That's an interesting idea but I don't want to do it this way. Since there are no just ores against coins but random all possible items, (with cooldown) the implementation is anyway too difficult. Especially if I extend the shop in the future. However, I have plans in the future to splitt the shop in various categories to make the whole "clearer"^^.
