### ISSUE TITLE
Quest book blank 

### ISSUE THREAD

**Issue by Jin16** [Freebi85/Dungeons-Dragons-Space-Shuttles#53]
So my game died and when i reloadet my game the quest book was like this https://imgur.com/a/m4aosRm
what to do ?

The world is from before update 3.3

**Comment by dierke9** [comment]
Did you try to use /bq_admin default load

**Comment by Jin16** [comment]
it worked, but all quest progress is gone T_T

**Comment by Freebi85** [comment]
Hello^^
Go to your backup folder and open "saves-->your world". Look for the "betterquesting" folder in the save, and copy "quest database" and "quest progress" files and paste them in the same folder of your primary world.

Due to the installed aroma backup mod everyone must have backups every 45 minutes.

If you don't hava a backup, (for whatever reasons) then use the "/bq_admin edit" command to complete any quests you're still needing to recover. Be sure to toss those rewards away^^
/bq_admin default load and bq_user refresh are only used to update the questbook to the newer version to have all new quests.
