### ISSUE TITLE
Crude oil unification

### ISSUE THREAD

**Issue by Landmaster** [Freebi85/Dungeons-Dragons-Space-Shuttles#587]
TF and GC oil have *exactly* the same function, but cannot be converted to/from each other. Is this intended?

If not, then I would suggest adding a Fluid Dictionary Converter recipe for this.

**Comment by Freebi85** [comment]
you should be able to use both for everything or  did I miss something?

**Comment by Landmaster** [comment]
They do not stack, and one cannot be used for the other's quests. This becomes a problem when, say, using bees, because the combs that the oil bees produce create both types of oil.

**Comment by Freebi85** [comment]
Wow no reason for a downvote my friend. 

I have a feeling that this is all about this quest because you are too lazy to find a galacticraft oil reservoir 🤔 😄 

Anyway, to your point: Since you can do pretty much anything and everything with both oils, there was no reason to convert them. (except completing 1 quest) 
But because I am not a monster I will gladly add a conversion recipe for the Fluid Dictnionary converter.

Protip: There is an item from pneumaticcraft which makes it easy to find oil reservoirs in the ground. I will add a quest for that. Don't know the name because not ingame atm^^

Cheers.
