### ISSUE TITLE
Version 6.5 Many duds stronghold (without end portal)

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#597]
Consider its not possible to progress through the quest without going to the end. It's extremely annoying that I have this many duds. I created a test world with the same seeds, and found 5 stronghold around my base and all duds,  
Eventually I did find one (using locate command repeatedly), but it was 10000 blocks away. In a normal gameplay I would never have found it without giving up on the pack.
seed: -2793105117587841914
I've played minecraft modded or not for over 10 years never hit this before. 
I think either world gen should be tweaked or there should be a way to create end portal with materials you have access to prior needing go there.

**Comment by Freebi85** [comment]
Hello :)
Well yes it happens due to the massive amount of extra dungeons, structures, underground biomes and worleys caves. But honestly, no one has ever had as much bad luck as you. RNGesusu you know 😄 

Anyway, there is a sidequest that will offer you enough endportal frames to create your own end portal in your base. It is the Enderium sidequest in ores alloy and smeltery tier 2.
Cheers

**Comment by LordHellscream** [comment]
i am assuming its one of the side quest branch, from where if i may ask?
