### ISSUE TITLE
After updating the game to V.7.0.b version it started doing this 

### ISSUE THREAD

**Issue by Sizii** [Freebi85/Dungeons-Dragons-Space-Shuttles#619]
For some reason Every time I try to start the game It start but Like the window of the loading part does not pop up It's just keep Java running on the background but nothing is popping up I don't know why. That didn't happen to me before it only happened after I updated it to the last version. I tried to get back to the previous update and now it does the same thing I just don't know where the issue is. I tried to give it some time to load but nope nothing happened. And I check the Task manager to know if the game is running or not  and I found that Minecraft is running but it's not showing on my Task bar.

**Comment by Freebi85** [comment]
Hello :)

This is sadly a common Twitch Issue when updating packs in gerenal in this launcher, Install the pack to a new profile, restart pc and try again or just switch to the MultiMC launcher because there are almost no issues with launching/installing and updating packs^^

Pls join our Discord Server if you need some more help, (Tech support channel)

Discord Server Link: https://discord.gg/eUajYmK

**Comment by Sizii** [comment]
Thank you <3
