### ISSUE TITLE
Some boosting mixture "enhanced" recipe does nothing

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#620]
Please report the following issues on this Github Issue Tracker:

- Not working / broken recipes 
- Proposals for new recipes or recipes that still need to be balanced.
- Suggestions for missing or additional integrations in machines
- Any problems with quests (description, spelling mistakes, task not recognized etc.)
- For Mod Issues check first official Mod Githubs if it has already been reported and if not report it there!

**Do NOT Report here:**
-Server problems or crashes. Use our helpdesk (tech-support) in our Discord Server to get some help with serverside issues. Discord Link: https://discord.gg/eUajYmK

**Comment by LordHellscream** [comment]
(Posted by accidient before finished typing)
Some boosting mixture recipe in carpenter (such as AA double battery) doesn't do anything different from the non-boosting version.

**Comment by Freebi85** [comment]
Hello :)
Boosting mixture doesent double the output of every recipes like the boosting mixture tooltip says, For the very expensive recipes it's mainly used to speed up the carpenter to almost instant crafting since there is no other way to speed it up.

In short:
Boosting mixture increases the production speed of all carpenter recipes. But but not necessarily the output.
