### ISSUE TITLE
NetherEx oregen broken

### ISSUE THREAD

**Issue by CalligoMiles** [Freebi85/Dungeons-Dragons-Space-Shuttles#633]
Ores do not seem to generate properly outside the default Hell biome, with most not appearing at all even after strip-mining  a dozen chunks.

(On a side note, ghasts also appear to be extremely rare. Don't know if that's intentional, but I only saw one and heard one more over dozens of hours in the nether)

**Comment by Freebi85** [comment]
Yes ghasts are rare that’s intentional. If you need more you have to find some structures with ghast spawner or raid the twilight forest. 

Also you have all the important taiga ores in non hell biomes (Pretty rare depending on ore and netherex biome) including cobalt from tinkers and quartz. Ardite is mainly in twilight forest. Stuff like nether iron or gold ore is only in hell biomes as small bonus.

**Comment by CalligoMiles** [comment]
That's all good theory, but I'm neither seeing any cobalt or ardite in NetherEx, nor finding any prometheum whatsoever outside Hell despite extensive mining.

**Comment by Freebi85** [comment]
This is not only the case in theory, but also in practice.
Is more common in gloomy Netherrack, Also check #ore-distribution in our Discord channel.
