### ISSUE TITLE
Way too many Carpenter receipes

### ISSUE THREAD

**Issue by Hexxonite** [Freebi85/Dungeons-Dragons-Space-Shuttles#653]
I am playing with some friends on a Server for a while now and the Carpenter-receipes are really taking overhand. Especially since we cant really automate the Crafting of them because it requires more than nine different Items in a receipe...

My friends and I have been wondering why there is no Modular-Machinery Advanced Carpenter like in some other modpacks e.g. Enigmatica Expert 2. Especially since you have added some other ones...

This would also benefit the crafting speed of receipes which is really annoyingly slow right now.

Hope you consider this :) Thanks.

**Comment by CloudyDash** [comment]
FYI, Carpenters are fully automatable from start to finish without the use of Packaged Auto or Refined Avaritia. You simply just need to have the AE/RS system keep the automation interface stocked with one of the items (eg: keep 8 steel plates in the input) and don't include that as part of the recipe.

**Comment by Freebi85** [comment]
Hey :) 
Cloudy Dash has already given the answer about automation. PackagedAuto, PackagedAutoEX and Refined avaritia can be used to automate 5x5, 7x7, 9x9 Tables with more then 9 items. 

It has always been the goal that you need more than one carpenter for automation. Some players have built factories with over 200 carpenters on the DDSS Discord.
Modular Machinery was added very late to improve everything around the Taiga alloys. The Master assembler was introduced because the rolling machine and the galacticraft compressor could not be automated properly.

As I am approaching a final version for ddss and starting an other project, I don't know if I will put as many hours into a new Modular Carpenter machine and transfer hundreds of recipes.

Anyway, I will think about it.

Cheers^^

**Comment by Hexxonite** [comment]
Hi and thanks for the quick response.

keeping one of the items in stock didn't really occur so thats a good tip for the future :)

So I guess even though we already have like 30~ish Carpenters I will have to make room for more ._.

Not that I have any technical knowledge of the workings, but as a suggestion maybe importing the structure for the machine directly from the said Modpack would be an option? Then you would just have to switch out the Block Id's? And for the recipes I think converting them 1:1 from Carpenters but with just half the amount of fluid it takes would be great already.
In contrast to the faster processing speed you would still have to build the multiblock but could automate 9 items at a time... But if the project is entering the final stage I guess it's understandable not to change it :)

Greetz
