### ISSUE TITLE
Recipe bug: Bowl of Promise strength II cannot be used in recipe only need strength I

### ISSUE THREAD

**Issue by LordHellscream** [Freebi85/Dungeons-Dragons-Space-Shuttles#660]
when crafting promise of productivity for example, a bowl of promise strength II cannot be used. Even though recipe need just strength I. (and the ore dictionary indicates strength II is also strength 1 and strength 0)

**Comment by Freebi85** [comment]
That's fine for me. I used specific bowls for specific recipes unlike Evilcraft default.

**Comment by LordHellscream** [comment]
@Freebi85 : You should re-consider. to make the lower level bowl of promise, You will need to manually downgrade the infuser. Not only that, if you have too much blood in the infuser. you will first need to manually pump them out before you can downgrade (remove the tenacity promise).
All this feel like a punishment for crafting while you are already ahead, Which doesn't make sense at all

**Comment by doomfur** [comment]
I also ask that you reconsider.  As far as I can tell, you can't downgrade the promise of tenacity to a lower level when you upgrade it, requiring you to create a separate infuser for lower tiers of recipes.  Seems rather counter-intuitive, especially since the in-game tooltip tells you that the higher tier bowl can be used for lower tier recipes.
