### ISSUE TITLE
zombie spawner work not in 4.1

### ISSUE THREAD

**Issue by ferrium42** [Freebi85/Dungeons-Dragons-Space-Shuttles#67]
after i update my world the zombie spawner stop working , i get one from a new chunk and this doesn´t work to , i test it with a drop of evil - nothing - other spawner work fine - is there any way to transport vanilla spawner ?

**Comment by Freebi85** [comment]
Hello =)
That's a mistake from Multibob. If you downgrade multimob to 1.0.4 the problem is temporarily fixed. I will consider it in the next update. 
Moving mobspawner is no longer possible without special devices like teleposer. But you can build your own mobspawner. Press R in JEI on a mobspawner to see what you need.
