### ISSUE TITLE
Dragon's underground lairs not spawning and error with ice and fire labeling stages

### ISSUE THREAD

**Issue by masterarcher300** [Freebi85/Dungeons-Dragons-Space-Shuttles#736]
Not sure what exactly is happening but on a server I run there seem to be no stage 4/5 underground lairs. I have confirmed via spectator that no lairs seem to have spawned. In addition, when hovering over a dragon, there seems to be problems identifying it in the mod which provides the window in the top left.

**Comment by Freebi85** [comment]
There are lairs but they are very rare. Best is to search in twilight forest because you can see them on the surface since the y level of the twilight forest is very low.

The one probe is known to have visual issues in multiplayer. Nothing to worrie about. There is not much i can do, that’s something to report to the mod author of top.

Pls join our discord server for more help 👍
