### ISSUE TITLE
Actually Additions / Galacticraft - recipe incompatibility issue

### ISSUE THREAD

**Issue by Dragonese** [Freebi85/Dungeons-Dragons-Space-Shuttles#737]
Both mods have a shapeless recipe for one coal/charcoal, where in AA should produce some tiny coal/charcoal and in Galacticraft it should produce fragmented carbon. In the server I play in and in my SP game the recipe produces fragmented carbon instead of tiny charcoal, and the Tier 0 Main Questline has a branch that is totally inaccessible without tiny charcoal. 

When opening the AA book for "Coal Stuff", there's two blank recipe forms and then one for the coal block. Galacticraft also has shapeless recipe for 4 coals/charcoals to produce fragmented carbon.

**Comment by Freebi85** [comment]
Tiny coal dosen’t exists in this pack and tiny charcoal can only be produced when smelting logs like the quest description says. Fragmented carbon is absolutely correct. 

Many things are changed in this pack and works differently. Recipes in Guidebook from mods are useless most of the time due to the heavy tweaks.
