### ISSUE TITLE
Hy, i have problem with botania's mana spreaders.

### ISSUE THREAD

**Issue by ballazs280** [Freebi85/Dungeons-Dragons-Space-Shuttles#759]
After few week of playing with dd&ss the botania mana spreaders started bad working. 
Video: https://www.youtube.com/watch?v=XyG5oiHq81o&feature=youtu.be
The mana burst position is bugging. I tried to restart the server, backup the map, move the mana spreader, add new mana spreader etc... Please help me

**Comment by Freebi85** [comment]
Im afraid i cant help you there. Didn't noticed that in singleplayer. 

I suggest you post your issue in the tech support channel "multiplayer" in my discord server. Maybe someone there can help you better than me. There seems to be some strange interaction here. But since it's not a recipe or anything else I could actively fix myself, it's hard to can I can help you there.
