### ISSUE TITLE
Tartaric gems are disappearing on death

### ISSUE THREAD

**Issue by SummitSummit** [Freebi85/Dungeons-Dragons-Space-Shuttles#76]
Tartaric gems are disappearing on death.  I don't know if it's strictly a Blood Magic issue, or a mod conflict.  When I die and go back and get my grave I get everything but my Tartaric gem back.  I've done it a couple times to make sure.

**Comment by Freebi85** [comment]
Yeah, that's hard to say. But since I have no authority to change anything in bloodmagic, the only one who can fix that is the mod author. You would have to open an issue on their site and describe exactly how, what and when it happened.

Whereby I am not sure if this is a issue because I read on reddit that is even normal oO
