### ISSUE TITLE
[Suggestion] Advanced Semiconductor Factory

### ISSUE THREAD

**Issue by dash16** [Freebi85/Dungeons-Dragons-Space-Shuttles#815]
At some point, creating a separate Carpenter for every kind of processor, microchip and control circuit gets out of hand.  My suggestion is to use Modular Machinery to create a new multiblock structure similar to the Master Assembler 2k20 and Advanced Alloy Smelting Factory called the Advanced Semiconductor Factory.  Feed Superglue into one tank and optional refined boosting mixture into the other tank to boost speed/yield of the output.  

- **Applied Energistics** Logic/Calculation/Engineering Processors, 1k/4k/16k/64k Storage/Fluid Storage Components
- **Refined Storage** 1k/4k/16k/64k Storage/Fluid Storage Parts
- **Tech Reborn** Overclocker/Transformer/Energy Storage Upgrades
- **Mekanism** Basic/Advanced/Elite/Ultimate Control Circuits
- **Rockhounding** Basic/Advanced Logic Chips
- **OpenComputers** Microchip (Tier 1/2/3)
- **etc**

**Comment by Freebi85** [comment]
Hello 🙂
Well using multiple carpenters and make a big factory with those was pretty much the intention behind the Ddss mechanic. So im not interested in a modular machine which will replace this specific recipes. Also, other people would then ask me to transfer all carpenter recipes into modular machines.

That would me take days and weeks of porting recipes to a new machine and since we are in a „pre-final“ release i don’t gonna make such big changes anymore. I’m limited to smaller fixes and improvements rn.
Already focused on another project.

No offense 😢
