### ISSUE TITLE
Modular Machines: Replace Tech Reborn machine ingredients with less TPS-laggy counterparts?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#819]
Freebi,

The current recipes for the Advanced Alloy Smeltery and the Master Fabricator 2k20 both involve a Tech Reborn machine as a "core" item to build the multi-block structure.  Especially with the use of the Rolling Machine, this block generates over 200ms of TPS lag.  In single-player it may not be an issue, but on multi-player servers, these can cause a good amount of lag.

Usual methods to "turn" off these machines do not work with the rolling machine; just sitting in the world causes the TPS.

![2020-04-23_17 04 36](https://user-images.githubusercontent.com/10191173/80331163-4b76f780-8815-11ea-96f5-998fdab48422.png)

If it's not a big deal, please consider replacing this machine with an equivalent, like Thermal Expansions Compressor (perhaps a hardened version to keep costs similar) that doesn't have this TPS problem.

Thanks for your consideration!

**Comment by Freebi85** [comment]
For now i don't gonna change that. This will break lots of machines and setups and actually I do not support servers. 

Also, you are scanning with a very old version of laggoogles. (i know a newer one isn't possible right now) But you cannot rely on the results. I would try again with 7.3 because the newest laggoogel version should work and come integrated with the pack. Then we'll see.
