### ISSUE TITLE
Energy Battery doesn't register in Quest Book

### ISSUE THREAD

**Issue by chadlupkes** [Freebi85/Dungeons-Dragons-Space-Shuttles#864]
Looks like the Energy Battery 2M quest requires an empty Battery.  I combined one that was full of energy, and I can't get it to register.  I'm going to create two new ones to see if that works.

**Comment by Freebi85** [comment]
This is correct. Since all this batteries from Integrated Dynamics have all the same item ID, i have to ask for a specific empty (or full)  battery. 

Otherwise the questbook would recognize and terminate all batteries questd with the first battery. The same applies to the next 4M battery quest. It's a clumsy solution, but the way this mod has built up this battery, I'm forced to do it this way.

**Comment by chadlupkes** [comment]
Hmm, tried full as well, and that didn't work either.

**Comment by Freebi85** [comment]
No it has to be empty and in worst case a combination of 2 fresh crafted ones.
But you can also complete the quests with /bq_admin complete [QuestID]
so you dont have to maker another one^^
