### ISSUE TITLE
Recipe to use Block of Iron in Mage's Workshop

### ISSUE THREAD

**Issue by chadlupkes** [Freebi85/Dungeons-Dragons-Space-Shuttles#865]
Ok,this one is odd.  When looking up the recipe on the uses of a block of iron, the Mage's Workshop shows two pages, but when you click on the arrows to go to Page 2, it shows 2/1 with no recipes and the page navigation arrows no longer work.  I captured video, if that will help.

**Comment by Freebi85** [comment]
Hello :)
Yeah this happens almost to every recipe due to an issue with refined storage. You will always get a blank page in the end. Nothing to worrie about but also nothing that would be fixed anymore in 1.12 by the devs afaik.

But pls report only issues with broken recipes or quests in this github. 
Everyhing else to the corresponding mod githubs bc i can't fix mod related issues. Thanks.

Cheers
