### ISSUE TITLE
(Suggestion) Disable Claim Chunk Menu's Chunk Loading

### ISSUE THREAD

**Issue by Tyroki** [Freebi85/Dungeons-Dragons-Space-Shuttles#866]
In the claim chunk menu, shift+clicking a claimed chunk automatically chunk loads it. There is absolutely no reason to make any chunk loading tech when we can simply do it for free.
I suggest disabling this function, otherwise there is no real purpose to having chunk loaders, beyond extending beyond your groups maximum chunk loading count. Sure it's 50 per person in a team, but early on, there is no reason to even start with the basic machines when you have up to 50 chunks loaded, per person... for free.

**Comment by Freebi85** [comment]
Uhm No.
Chunk loading is for free in my pack. The other "machines" are there because Server Admins like to block these functions for TPS reasons or to force players to build heavier chunkloaders like those from chickens or whaterver.

Of course there are also admins like in your case who are not interested in setting up specific FTB Ranks and permissions for their players. So it's just default and Free for all.

Cheers
