### ISSUE TITLE
CPU's not recognizing each other

### ISSUE THREAD

**Issue by keebster** [Freebi85/Dungeons-Dragons-Space-Shuttles#872]
The CPU's Item number 5933/0 /1 and /2 Do not see the tier below it within the system.

**Comment by Freebi85** [comment]
within which system?

**Comment by keebster** [comment]
Oh terribly sorry for not saying. We are using a Refined Storage computer system. I can create the 5933/0 Item as it doesnt require another cpu. But the 5933/1 does not recognize the pattern or the item of 5933/0 in the computer. and the 5933/2 does not recognize the pattern or the item 5933/2

**Comment by keebster** [comment]
I notice this while trying to make the Solar Panel VII. As it does not recognize any of those CPU's

**Comment by Freebi85** [comment]
I see. Well since the CPU recipes are default by Opencomputer it's either a problem with refined storage or with the item of opencomputers. In both cases i can't fix this myself. You should report this to one of them. Try beforhand other recipes which requires this cpus to be sure like the turbine computer port.

Cheers
