### ISSUE TITLE
Artisan Automation - Upgrade modules?

### ISSUE THREAD

**Issue by Danekjovax** [Freebi85/Dungeons-Dragons-Space-Shuttles#920]
Hi, Freebi,

Overall, I really like the Artisan workshop mod in this modpack; it gives a unique mechanic that puts this modpack above the others in a way I really like, but there was one thing that I had a question on and sent you a DM about it, but you must have missed seeing it, so I'll simply post the question again here:

 I just wondered if you were planning on putting any of the Artisan Automation upgrades in the modpack for use in the Mechanical Artisan?

The mod developer provided this link for information on the upgrades:
https://artisan-automation.readthedocs.io/en/latest/upgrades/

I think this would add a great dimension of playability to a great modpack, coinciding nicely with the growing automation and industrialization as one progresses in this modpack.

Please consider adding these upgraed modules.  Thanks!
:2)

**Comment by Freebi85** [comment]
Hello Sir 😃 
The use of artisan tables was never intended for automation in ddss. What needed to be automated I transferred with a lot of effort to the carpenters at that time. Nevertheless, this fantastic feature was implemented by the artisan dev later. Which is quite useful and helpful for certain things.

Nevertheless, upgrades would be too strong for that. Since I cannot limit upgrades to special workshops, all carpenter recipes are affected and this would be a gamebreaker in a way. For this reason I unfortunately have to decline.
