### ISSUE TITLE
autocrafting using master assembler is getting stuck

### ISSUE THREAD

**Issue by DoomSquirter** [Freebi85/Dungeons-Dragons-Space-Shuttles#928]
Is it a known limitation that it only makes a stack of something like heavy plates?

if I say to craft 100, it'll make 64 but the crafting task will just stay stuck forever waiting on the other 36.  I just made the multi and even made the really large 32 item inputs for them thinking that might fix it.  

basically, making heavy plates for gc.  

not having any automation issue with alloy smelting factory nor am I seeming to have issues making other things in the assembler.  but definately the heavy plates.  not running latest but previous update still.

**Comment by Freebi85** [comment]
Hello.

There is no limitation on my part. In 99% of the cases the master assembler is stuck because the recipes consume more power than your energy port can deliver. (some recipes much more then others) The machine is not smart enough to stop the process in this case. So I would increase the energy port to get higher transfer rates.

**Comment by DoomSquirter** [comment]
yeah, but the items would be stuck in the input no?  and that's not the case.  unless you're thinking it just ate the items...

I upgraded from reinforced to huge energy inputs and queued up 100 t2 heavy plates and it made 60 and now 40 are just stuck in crafting screen.  I watched the energy input and it never went down in power noticeably

**Comment by Freebi85** [comment]
I do not know what to tell you here. It's a recipe like any other I have designed for this machine. It may not work well with Galacticraft components but that is just speculation. And since I am neither the mod developer of ModularMachines nor Galacticraft, there is not much I can do to improve this process.

**Comment by DoomSquirter** [comment]
ok, thanks for trying.  I appreciate it

**Comment by DoomSquirter** [comment]
so I got to venus and got draconium ore.  queued up in alloy smelter 1600 ingots and walked away.  I know I have enough power lava and booster going in at rates that can't be exceeded.   Yet I did come back to 640 something ingots still stuck in autocrafting, and when cancelled, nothing is put back in ae so items were lost.  I think the modular machines are losing stuff when it gets overwhelmed.  not that you can do anything about this, just saying I am 99% certain that is where the problem lies.
