### ISSUE TITLE
Missing recipe for BloodWood planks from bloodwood 8266/15 in sawmill (available only in manufactory)

### ISSUE THREAD

**Issue by Galicjanin** [Freebi85/Dungeons-Dragons-Space-Shuttles#931]
Missing recipe for BloodWood planks from bloodwood 8266/15 in sawmill (available only in manufactory)
8266/0 can be changed into planks in both mashines.
Other Bloodwoods 8266/1-14 obtained with silk-touch are unusable in any way.

**Comment by Freebi85** [comment]
Thanks for reporting. But it was already covered here #922 and should be fixed in the next and last patch. 
Remember that the pack is in a pre final stage. Only a few things will be changed or adjusted as I am ending this project after 2 long years^^ 
Because of other projects I don't have the time for.
