### ISSUE TITLE
Crash and now unable to play on my world. Version 8.0_R1

### ISSUE THREAD

**Issue by ThewABwAB** [Freebi85/Dungeons-Dragons-Space-Shuttles#945]
[crash-2020-10-30_12.30.05-client.txt](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/5464835/crash-2020-10-30_12.30.05-client.txt)
![image](https://user-images.githubusercontent.com/38288546/97700798-b3e8af00-1aac-11eb-953e-35c367bf853d.png)

**Comment by ThewABwAB** [comment]
Downgraded to version 7.4a. Can now keep playing on the same world.

**Comment by Freebi85** [comment]
A chameleon walked over a bibliocraft item and crashed. Pack version doesent matter. Can happen every time bc there are some incompatibility between both in specific cases and the mod version is the same since both mods aren’t updated long ago. Worstcase remove/kill all entities with a command or use a backup.
Please use the tech support channel in our discord server for further tech- related issues. Thank you

**Comment by ThewABwAB** [comment]
Thank you! killed all chameleons in my vicinity now XD
Tried to start up a few times with the same version and it crashed.. however worked without issues after changing.. don't know what changed :P
