### ISSUE TITLE
I try to open and join my server, but it has an issue where there is an unregistered item "wooden door"

### ISSUE THREAD

**Issue by TacTwicePeng** [Freebi85/Dungeons-Dragons-Space-Shuttles#970]
I have been playing my server with some friends for a while now, but now i get an error when i try to join it where there is an unregister item "wooden door". i have been playing it for months and i dont want to lose our progress and money from keeping the server up

**Comment by Freebi85** [comment]
Everyone using the curseforge launcher isn’t able to join their server anymore since yesterday. Not even singleplayer works correctly sometimes. Launching a modpapack through curseforge will corrupt many files which ends in a fatal error of registry mismatches and such. Something to do wit a recent Microsoft/minecraft/Mojang update or whatever. 

The solution found was to use another launcher like GDlauncher or ATLauncher and reinstall the pack on this new launcher from scratch. And do not migrate (copy paste) under any circumstances files from the curseforge launcher to the new one except singleplayer worlds from save folder if needed.

if you don’t like to change launcher, consider to join curseforges discord server for some advice. 

I can’t help more then this im sorry. 

Cheers 🍻
