### ISSUE TITLE
Getting an error on own personal server that is fatally missing registry entries and occasionally it says missing wooden_door

### ISSUE THREAD

**Issue by Gandy9913** [Freebi85/Dungeons-Dragons-Space-Shuttles#971]
I have been trying to get the modpack to work on my own personal server and had it working for all of a day before this started happening, anytime anyone tries to join it either gives them the error "fatally missing registry entries" or something to do with missing wooden_door. I have tried everything I possibly can with switching out config files and freshly downloading them to no avail, as well as when someone tries to join it gives a giant list of errors to do with achievements. Above their name it also says failed to sync registry data with server.

Here is my latest log from my latest attempt
[latest.log](https://github.com/Freebi85/Dungeons-Dragons-Space-Shuttles/files/9961912/latest.log)

**Comment by Freebi85** [comment]
Everyone using the curseforge launcher isn’t able to join their server anymore since yesterday. Not even singleplayer works correctly sometimes. Launching a modpapack through curseforge will corrupt many files which ends in a fatal error of registry mismatches and such. Something to do wit a recent Microsoft/minecraft/Mojang update or whatever.

The solution found was to use another launcher like GDlauncher or ATLauncher and reinstall the pack on this new launcher from scratch. And do not migrate (copy paste) under any circumstances files from the curseforge launcher to the new one except singleplayer worlds from save folder if needed.

if you don’t like to change launcher, consider to join curseforges discord server for some advice.

I can’t help more then this im sorry.

Cheers 🍻
